---
# HTTP
- name: "Add password for http keystore" 
  command: "echo '{{ elasticsearch.certificates.http_certificate.password }}' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.keystore.secure_password --force"

- name: "Add password for http truststore" 
  command: "echo '{{ elasticsearch.certificates.http_certificate.password }}' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.truststore.secure_password --force"

# Transport
- name: "Add password for transport keystore" 
  command: "echo '{{ elasticsearch.certificates.transport_certificate.password }}' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password --force"

- name: "Add password for transport truststore" 
  command: "echo '{{ elasticsearch.certificates.transport_certificate.password }}' | /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password --force"

# Setup passwords
- name: "Setup passwords for builtin users"
  command: "/usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto -b -u https://{{ hostvars[groups[elasticsearch_primary_master_group_name][0]].ansible_default_ipv4.address }}:{{ http.port }}"
  register: _builtin_passwords
  become: true
  notify: "Restart Elasticsearch"

# Process automatic password change
- name: "Print registered"
  debug:
    msg: "{{ _builtin_passwords }}"

        # "stdout_lines": [
        #     "Changed password for user apm_system",
        #     "PASSWORD apm_system = ZNWAPMHetbInZA2ZXeal",
        #     "",
        #     "Changed password for user kibana_system",
        #     "PASSWORD kibana_system = 5ejYXI8LT9TnMSIKB9u4",
        #     "",
        #     "Changed password for user kibana",
        #     "PASSWORD kibana = 5ejYXI8LT9TnMSIKB9u4",
        #     "",
        #     "Changed password for user logstash_system",
        #     "PASSWORD logstash_system = PGXHU0eV5nQUFCy3mXRD",
        #     "",
        #     "Changed password for user beats_system",
        #     "PASSWORD beats_system = KSr7Y7KjJc7muRivcP6A",
        #     "",
        #     "Changed password for user remote_monitoring_user",
        #     "PASSWORD remote_monitoring_user = QcpEBTW4ybJkTiv4fyVF",
        #     "",
        #     "Changed password for user elastic",
        #     "PASSWORD elastic = Ul3zJHWqf4asn7Q0SCgQ"
        # ]