---
- name: "Preflight Checks"
  include_tasks: "00-preflight-checks.yml"

- name: "Configure Elasticsearch"
  include_tasks: "01-configure.yml"

- name: "Setup passwords"
  include_tasks: "02-setup-passwords.yml"
