---
- name: "Start Elasticsearch"
  systemd:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes
    state: started
  become: true

- name: "Restart Elasticsearch"
  systemd:
    name: elasticsearch
    daemon_reload: yes
    state: restarted
  become: true
